# Generated by Django 3.0.5 on 2020-05-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0002_auto_20200507_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=64)),
                ('last', models.CharField(max_length=64)),
                ('journeys', models.ManyToManyField(blank=True, related_name='passengers', to='journeys.Bus')),
            ],
        ),
    ]
